# Generated by Django 5.1.5 on 2025-01-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
